# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Ab Optimis Discamus
  la: Ab Optimis Discamus
email: gerardkeiser@gmail.com
description:
  en: Reviews for Latin materials
  la: De Rebus ad Latinam Discendam
index:
  en:
  la: initium.html
feed:
  en: /feed.xml
  la: /fluxus.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://discam.us" # the base hostname & protocol for your site
twitter_username:
github_username: Lactantius

# Build settings
markdown: kramdown
